# Site
name: 'شباب العلا'
description: 'شباب العلا'
logo: 'assets/images/logo.jpeg'
favicon: 'assets/images/favicon.ico'
baseurl: '/'
disqus: ''
email: ''
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    hamza:
      name:           حمزة مرزوق
      site:           لا يوجد موقع الكتروني
      avatar:         assets/images/profile.png
      bio:            لا يوجد سيرة ذاتية
      email:          لا يوجد بريد إلكتروني
      twitter:        لا يوجد حساب تويتر

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: hamza
      avatar: assets/images/gentle.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
